# This workflow autogenerates sphinx documentation and deploys it to Github pages
# Many thanks to: https://stackoverflow.com/questions/57989790/using-github-actions-to-publish-documentation

name: Sphinx Autodeploy

on:
  release:
    types: [published]

jobs:
  release-sphinx:
    runs-on: ubuntu-latest
    container:
      image: python:3.7

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.1

      - name: Build documentation
        run: |
          pip3 install sphinx sphinx-rtd-theme
          python3 -m sphinx -b html -c docs/ -j 4 docs/ docs/_build
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@3.5.6
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          BRANCH: master
          FOLDER: docs/_build
          COMMIT_MESSAGE: Building documentation
